services:
  build-frontend:
     image: dind-first-step
     command: bash -c "apt update && apt install make"
     entrypoint:
       - bash
       - -c
       - "[[ \"$PROD_BUILD\" == \"true\" ]] && make fe-prod || make fe-dev"

